# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab04/mac_tree/mac_tree.srcs/sources_1/ip/c_addsub_1/c_addsub_1.xci
# IP: The module: 'c_addsub_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab04/mac_tree/mac_tree.gen/sources_1/ip/c_addsub_1/c_addsub_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab04/mac_tree/mac_tree.srcs/sources_1/ip/c_addsub_1/c_addsub_1.xci
# IP: The module: 'c_addsub_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab04/mac_tree/mac_tree.gen/sources_1/ip/c_addsub_1/c_addsub_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
