# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/mult_32_20_lm/mult_32_20_lm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/adder/adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/multiply/multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# XDC: c:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/adder/adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: C:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/multiply/multiply.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# XDC: c:/Users/USER/Desktop/SR/SR-2024S-main/SR-2024S-main/lab07/mass_centroid/mass_centroid.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
