# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0.xci
# IP: The module: 'hdmi_vga_vp_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/ip/c_add/c_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add || ORIG_REF_NAME==c_add} -quiet] -quiet

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0.xci
# IP: The module: 'hdmi_vga_vp_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/ip/c_add/c_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_add || ORIG_REF_NAME==c_add} -quiet] -quiet

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_1_0/hdmi_vga_vp_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
