# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
# IP: The module: 'hdmi_vga_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
# IP: The module: 'hdmi_vga_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mateusz/Desktop/studia/AiR/SR/Verilog/MP_lab6_107/Lab6_RGB_YCbCr/dzialajacy_tor_wizyjny.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
