# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# IP: ip/adder/adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: ip/multiply/multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# Block Designs: bd/hdmi_vga/hdmi_vga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga || ORIG_REF_NAME==hdmi_vga} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_0_0/hdmi_vga_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_rgb2vga_0_0/hdmi_vga_rgb2vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_vga_rgb2vga_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_0/hdmi_vga_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_1_0/hdmi_vga_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_1_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_1_0} -quiet] -quiet

# IP: bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_vga_vp_0_0 || ORIG_REF_NAME==hdmi_vga_vp_0_0} -quiet] -quiet

# IP: ip/adder/adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: ip/multiply/multiply.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab06/treshold_YCbCr/treshold_YCbCr.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab06/treshold_YCbCr/treshold_YCbCr.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab06/treshold_YCbCr/treshold_YCbCr.gen/sources_1/bd/hdmi_vga/hdmi_vga_ooc.xdc
