# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab07/mass_centroid/mass_centroid.gen/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab07/mass_centroid/mass_centroid.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab07/mass_centroid/mass_centroid.gen/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
