# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc

# XDC: c:/Users/janro/Pulpit/AGH_FILES/SR-2024S/lab05/LUTsss/LUTsss.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
